name: GitHub CI
on: 
  push:
    branches: [ master ]
    tags:
      - '**'
  workflow_dispatch:
  pull_request:

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  freebsd_build:
    strategy:
      matrix:
        include:
          - arch: amd64
            artifact: subconverter_freebsd64
    runs-on: ubuntu-latest
    name: FreeBSD ${{ matrix.arch }} Build
    steps:
    - name: Checkout base
      uses: actions/checkout@v4
    
    - name: Setup FreeBSD VM and build
      uses: vmactions/freebsd-vm@v1.1.0
      with:
        usesh: true
        prepare: |
          pkg install -y -q git cmake gmake gcc | tee build.log
        run: |
          SHA=$(git rev-parse --short HEAD)
          sed -i '' 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
          git clone https://github.com/gaoyuyun/subconverter.git
          cd subconverter
          chmod +x scripts/build.freebsd.release.sh
          bash scripts/build.freebsd.release.sh
          mv subconverter /output/
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: /output/subconverter
    
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
      run: tar czf ${{ matrix.artifact }}.tar.gz -C /output subconverter
    
    - name: Draft Release
      if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.artifact }}.tar.gz
        draft: true
